from flask import render_template
import connexion

# Create an instance of the App using connexion instead of flask
app = connexion.App(__name__, specification_dir="./")

# Read the swagger.yml file to configure the endpoints
app.add_api("swagger.yml")

@app.route("/")
def home():
    """
    This renders the home.html on
    http://localhost:5000
    :return:       the html page generated by home.html
    """
    return render_template("home.html")

if __name__=="__main__":
    app.run(debug=True, host= "0.0.0.0", port=5000)
